Repository wecode-bootcamp-korea/43-2nd-See-Other-backend, pull requests merged in 2023-04, with the labels that each got.

#7 [43기 김승태] 예매 옵션 필터
  api/controllers/reservationController.js
  api/models/builder.js
  api/models/movieDao.js
  api/models/reservationDao.js
  api/routes/index.js
  api/routes/reservationRouter.js
  api/services/reservationService.js
  api/utils/enum.js
Labels: 멘토 리뷰 요청

#10 [43기 김승태] 예매 시간 옵션 read
  api/controllers/reservationController.js
  api/models/builder.js
  api/models/reservationDao.js
  api/routes/reservationRouter.js
  api/services/reservationService.js
  db/migrations/20230405083358_create_reserved_seats_table.sql
Labels: 멘토 리뷰 요청

#11 [43기 김승태] 예매 좌석 read
  api/controllers/reservationController.js
  api/models/builder.js
  api/models/reservationDao.js
  api/routes/reservationRouter.js
  api/services/reservationService.js
  api/utils/enum.js
Labels: 수정 요청

#9 [43기 강혁주] Reservation Detail
  api/controllers/index.js
  api/controllers/reservationController.js
  api/controllers/userController.js
  api/models/index.js
  api/models/reservationDao.js
  api/models/userDao.js
  api/routes/index.js
  api/routes/reservationRouter.js
  api/services/index.js
  api/services/reservationService.js
  api/services/userService.js
  api/utils/get-endtime.js
  server.js
Labels: Conflict 해결 요청
